# Site settings
title: 菩提树下有只蝉
subtitle: 不鸣则已，一鸣惊人
email: xsf72006 AT gmail.com
description: > # this means to ignore newlines until "baseurl:"
  TimmyXu的个人博客，内容主要是IT技术，传统文化，个人日记。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timmyxu.me" # the base hostname & protocol for your site
#url: "localhost:4000"
timezone: 'Asia/Shanghai'
permalink: /:categories/:title/

# Build settings
markdown: kramdown

# Categories settings
category_title_prefix: "归档："

# Tags settings
tag_title_prefix: "标签："