# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 别㲌android (don/t android)
email: machangkun@me.com
description: 很多事不做为好
# this means to ignore newlines until "baseurl:"
# 很多事不做为好,
#   之前被java坑了, 从2015年开始被Android坑.
#   费劲千辛万苦,
#   貌似爬出来了一点,
#   回头看看,
#   其实坑不深,
#   也不大.
#   同学们应该能比我更快的爬出来.
#   嗯, 3个月吧.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://lornally.github.io" # the base hostname & protocol for your site
twitter_username: machangkun
github_username:  lornally

# Build settings
# markdown: kramdown







# Jekyll configuration

name: don/t 别㲌
# description: 很多事不做为好

# Url is currently only used only for the RSS feed in feed.xml
#url: http://lornally.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
# baseurl: ''

defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts" # 以前的 `post`， 在 Jekyll 2.2 里。
    values:
      layout: "post"




share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github:
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: streetturtle
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
